### ISSUE TITLE
URL and accessed date missing from references

### ISSUE THREAD

**Issue by 7hx1e** [jgm/citeproc#100]
The new version adds hyperlink to the titles. However, the URL and accessed date is removed from the references.
I tried setting link-bibliography to false, which only removed the hyperlink on the title, but the URL and accessed date are still missing.

I am wondering how to add them back to my references?

**Comment by jgm** [comment]
Whether these appear is controlled by the CSL style.  Are you using the same style as before? Are you sure the style calls for them to appear?

When you say "new version," you're comparing which version to which?

**Comment by 7hx1e** [comment]
I was using the same CSL file as before (springer-basic-author-date.csl) but the reference list exported are different.
Pandoc 2.17 vs 2.14.2.

**Comment by jgm** [comment]
You need to give us a minimal example so we can reproduce the issue.

**Comment by 7hx1e** [comment]
Thanks for trying to help me. Not sure what caused the difference reference list results between 2.14.2 and 2.17. However, I customized the springer-basic-author-date CSL to force URL and Accessed Date to be shown on all entry type and that seemed solved the problem. Closing this ticket.

**Comment by 7hx1e** [comment]
Thanks for trying to help me. Not sure what caused the difference reference list results between 2.14.2 and 2.17. However, I customized the springer-basic-author-date CSL to force URL and Accessed Date to be shown on all entry type and that seemed solved the problem. Closing this ticket.
