### ISSUE TITLE
incorrect Dutch translation of "edition", should be "editie", not "druk"

### ISSUE THREAD

**Issue by ffel** [jgm/citeproc#109]
`locaes/nl-NL.xml` lines 61-65 should read

```xml
    <term name="edition">
      <single>editie</single>
      <multiple>edities</multiple>
    </term>
    <term name="edition" form="short">ed.</term>
```
The correct Dutch translation of edition is "editie", not "druk" (which is Dutch for "imprint")

**Comment by jgm** [comment]
These locales come from upstream, so you should inquire there.
https://github.com/citation-style-language/locales

**Comment by jgm** [comment]
We will migrate any changes from upstream.

**Comment by denismaier** [comment]
I've opened a PR https://github.com/citation-style-language/locales/pull/260
