### ISSUE TITLE
Citeproc html error for csl styles that do not print titles

### ISSUE THREAD

**Issue by chemicus** [jgm/citeproc#112]
**Command used**
```echo "@article{test,author={Author, First},title={Title},journal={Journal},year={1234},url={example.com}}" | pandoc --citeproc -f biblatex --mathjax --csl=https://raw.githubusercontent.com/citation-style-language/styles/master/angewandte-chemie.csl```

**Excerpt from changelog of 2.14.2**
> [...]. If a DOI, PMID, PMCID, or URL field is present but not explicitly rendered, the title (or if no title, the whole entry) is hyperlinked.

**Description of the problem**
The above mentioned changes in the citeproc code seem to be responsible for changes in the output using a csl-style that does not print titles (like [this](https://raw.githubusercontent.com/citation-style-language/styles/master/angewandte-chemie.csl)). Due to the presence of a url-field in the example bibtex entry, version 2.14.2 automatically adds a hyperlink to the citation as expected and documented. However, apparently a ` </div><div class="csl-right-inline">` is missing here.
The problem only affects csl-styles that do not print titles, but is still present in the current version 2.18.

**Output of Pandoc 2.14.1**
```
<div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-test" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">F. Author, <em>Journal</em> <strong>1234</strong>.</div>
</div>
</div>
```

**Output of Pandoc 2.14.2**
```
<div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-test" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><a href="https://example.com">[1]F. Author, <em>Journal</em> <strong>1234</strong></a></div>.
</div>
</div>
```

**Output of Pandoc 2.18**
```
<div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-test" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><a href="https://example.com">[1]F. Author,
<em>Journal</em> <strong>1234</strong></a></div>.
</div>
</div>
```

**Pandoc version?**
Pandoc 2.14.1, 2.14.2, 2.18 on Ubuntu 20.04.4 LTS

**Comment by benrbray** [comment]
Sure, I will look into it, thanks for reporting.

**Comment by jgm** [comment]
@chemicus the fix should start to appear in nightly versions of pandoc after the next nightly build.
