### ISSUE TITLE
Error in latex generation of portuguese quotes in CSLReferences field

### ISSUE THREAD

**Issue by igormcoelho** [jgm/citeproc#123]
I'm experiencing some error with `pandoc 2.19.2` using `--citeproc` option, where my language is portuguese `lang : pt-BR`.
When I use `lang : en` it works fine, and generates like this:
```
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-autor2021}{}}%
LastName, First Name. 2021. {``Title''} Other things.
```
The `{``Title''}` seems to be correct... but when I shift to `lang : pt-BR`, it generates like this: `LastName, First Name. 2021. {"Title"} Other things.`
This is wrong, because of `{"` and `"}` elements... and generate this error:
```
Runaway argument?
! Paragraph ended before \language@active@arg" was complete.
```

My only solution was to add this ugly thing as a post-pandoc script:

```
pandoc ... output.tex
csplit output.tex /begin{CSLReferences}/ '{*}'
sed -i 's/{"/{``/g' xx01
sed -i 's/"}/''}/g' xx01
cat xx00 xx01 > output.tex
```

Meaning that I manually split the generated .tex file into two, and then replace `{"` and `"}` by their correct counterparts.
Is there any configuration that I can make pandoc work fine with non-english language in biblatex, without this fix?
Thanks!

**Comment by jgm** [comment]
That's strange; I don't understand why it is doing this and not including the proper localized unicode characters; they are in the locale. I'll need to investigate.

**Comment by igormcoelho** [comment]
Thanks for the reply... to make investigation simpler, I'll share my setup, that was luckly made with Docker and vscode Dev Containers plugin... so it's 100% reproducible.

.devcontainer/devcontainer.json

```
{
	"name": "C++",
	"build": {
		"dockerfile": "Dockerfile"
	},
	"remoteUser": "root"
}
```

Dockerfile

```
FROM mcr.microsoft.com/devcontainers/cpp:0-debian-11

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install \
        texlive texlive-base texlive-latex-extra texlive-latex-recommended \
        texlive-bibtex-extra biber \
        texlive-xetex texlive-fonts-extra \
        texlive-science \
        texlive-lang-portuguese
        
RUN wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
RUN sudo dpkg -i pandoc-2.19.2-1-amd64.deb

RUN wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.13.0b/pandoc-crossref-Linux.tar.xz
RUN mv pandoc-crossref-Linux.tar.xz /usr/local/bin/
RUN (cd /usr/local/bin/ && tar xf pandoc-crossref-Linux.tar.xz)
```

And I don't understand how this locale situation works, but this is the output of `locale` command, inside the container:

```
root@container $ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by jgm** [comment]
[Here's a repro with trypandoc](<https://pandoc.org/try/?params=%7B%22text%22%3A%22---%5Cnlang%3A+%27pt-BR%27%5Cnreferences%3A%5Cn-+author%3A%5Cn++-+family%3A+Salam%5Cn++++given%3A+Abdus%5Cn++container-title%3A+%5C%22Elementary+particle+theory%3A+Relativistic+groups+and%5Cn++++analyticity.+Proceedings+of+the+eighth+Nobel+symposium%5C%22%5Cn++editor%3A%5Cn++-+family%3A+Svartholm%5Cn++++given%3A+Nils%5Cn++event-date%3A+1968-05-19%2F1968-05-25%5Cn++event-place%3A+Aspenäsgarden%2C+Lerum%5Cn++id%3A+salam%5Cn++issued%3A+1968%5Cn++page%3A+367-377%5Cn++publisher%3A+Almquist+%26+Wiksell%5Cn++publisher-place%3A+Stockholm%5Cn++title%3A+Weak+and+electromagnetic+interactions%5Cn++type%3A+paper-conference%5Cn---%5Cn%5Cn%40salam+%5Bp.+370%5D+says+some+interesting+things.%22%2C%22to%22%3A%22plain%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Atrue%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3A%22pygments%22%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D>)

**Comment by jgm** [comment]
Mystery solved? I looked at `chicago-author-date.csl`, the style pandoc uses by default, and it contains overrides for Portuguese:

```xml
  <locale xml:lang="pt">
    <terms>
      <term name="editor" form="verb">editado por</term>
      <term name="editor" form="verb-short">ed.</term>
      <term name="container-author" form="verb">por</term>
      <term name="translator" form="verb-short">traduzido por</term>
      <term name="translator" form="short">trad.</term>
      <term name="editortranslator" form="verb">editado e traduzido por</term>
      <term name="and">e</term>
      <term name="no date" form="long">s.d</term>
      <term name="no date" form="short">s.d.</term>
      <term name="in">em</term>
      <term name="at">em</term>
      <term name="by">por</term>
      <!-- PUNCTUATION -->
      <term name="open-quote">"</term>
      <term name="close-quote">"</term>
    </terms>
  </locale>
```

I'm curious why these are here!

Removing the overrides for the quotes will fix this.
Or you may want to try a different style.

**Comment by igormcoelho** [comment]
Oh! Maybe someone wrongly fixed these?
Now I see... it's interesting because I wanted to change the style and didn't know how :joy: 
So, I did my own fix, removing these quotes, and it works fine with `--bibliography bibliography.bib --csl=chicago-author-date-fix-br.csl`

Thanks a lot!

**Comment by igormcoelho** [comment]
Indeed, someone really messed up :joy:... the correct solution is supposed to be:
```
      <term name="open-quote">“</term>
      <term name="close-quote">”</term>
```

It's here on this repo the correct one: https://github.com/citation-style-language/locales/blob/master/locales-pt-BR.xml#L163-L164
But chicago is wrong :joy: https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl#L68-L69

**Comment by jgm** [comment]
Yes, the default for citeproc is the "correct one," but someone altered the chicago-author-date style intentionally to override it.  I have no idea why but perhaps if you search the git history of the styles repository, you'll find the answer.

**Comment by igormcoelho** [comment]
Yep, I guess some change in february by a fellow brazilian updated this during some translation... I'll try to revert this part of the change there.

**Comment by jgm** [comment]
If your changes are accepted, let us know and we can use the new version in pandoc.

**Comment by igormcoelho** [comment]
Ok @jgm , I think it may be fixed on that side ;)

By the way, I couldn't understand where the problem from `"` came from.. who translates csl to latex, is it pandoc or latex itself? :thinking: And if it's pandoc, maybe a future strategy could be to detect open and close `"` on csl, and if it's the case, transform them into typographic quotes? This came from another discussion there...
https://github.com/citation-style-language/styles/pull/6317#issuecomment-1331224252

In any case, I really think the change in style there needs to be reverted, so no fix here will be needed, but I'm just trying to better understand how all these things work :)

**Comment by jgm** [comment]
If citeproc says to use a `"`, pandoc will pass the `"` through to LaTeX.
At least with the current version of pandoc, it doesn't cause an error.  I get the following with pdflatex

<img width="668" alt="Screen Shot 2022-11-29 at 6 30 37 PM" src="https://user-images.githubusercontent.com/3044/204693221-0069b961-19bc-4e27-b695-2b4381a536ef.png">

and with xelatex:

<img width="687" alt="Screen Shot 2022-11-29 at 6 31 01 PM" src="https://user-images.githubusercontent.com/3044/204693270-aae27d79-a2d5-4725-b104-d788da7b3af2.png">

**Comment by jgm** [comment]
You probably need to adjust something in your custom template.  Compare it with the default one in pandoc.

**Comment by jgm** [comment]
Let me know when the  changes are accepted over there.  so far the style has not changed.

**Comment by igormcoelho** [comment]
Hi @jgm , the PR has been accepted at https://github.com/citation-style-language/styles/pull/6317
The problematic lines have been removed. So, now pandoc can also do the same fix, if possible :)
