### ISSUE TITLE
Installing the executable

### ISSUE THREAD

**Issue by sati-bodhi** [jgm/citeproc#124]
I install `citeproc` with `cabal install` and ended up with this warning:

```
Warning: You asked to install executables, but there are no executables in
target: citeproc. Perhaps you want to use --lib to install libraries instead.
```

I'd like to try out the executable to [add citation processing to non-Haskell projects](https://hackage.haskell.org/package/citeproc). 

Also, I'd like to know how to use `citeproc` with pandoc in place of `pandoc-citeproc`.

**Comment by jgm** [comment]
Use `-fexecutable` if you want to build the executable.

**Comment by jgm** [comment]
Instructions for using pandoc with (built in) citeproc are in the pandoc user's manual.
