### ISSUE TITLE
[Help] Author only citations BibTex

### ISSUE THREAD

**Issue by bambirombi** [jgm/citeproc#125]
I have not found the syntax for author only citations. I know that [-@Allen.etal2000] gives me (2000) but,

I want this: `Allen et al.` without parenthesis and without year.

**Comment by jgm** [comment]
There is no syntax for this.  Anyway, your question is really about pandoc, I think (since citeproc itself doesn't have a syntax like this).  If you search on the pandoc issue tracker, including closed issues, you'll find some discussions.
