### ISSUE TITLE
Stopword capitalized after abbreviation

### ISSUE THREAD

**Issue by adunning** [jgm/citeproc#127]
Stopwords appear to be capitalized incorrectly after an abbreviation. For example, using pandoc 2.19.2:

```shell
pandoc -t plain -C << EOT 
---
references:
- id: test
  title: >-
    Test, MS., to the stopword 'to'
---

@test

EOT
```

Zotero renders this title as “Test, MS., to the Stopword ‘to’” but Pandoc produces “Test, MS., To the Stopword ‘to’”.

(In case this seems far-fetched, the actual title in which I encountered this is [*Catalogue of the printed books and manuscripts bequeathed by Francis Douce, Esq., to the Bodleian Library*](https://hdl.handle.net/2027/chi.73330782).)

**Comment by jgm** [comment]
Confirmed that this fixes it:
```
“Test, MS., to the Stopword ‘to’.” n.d.
```

**Comment by adunning** [comment]
Many thanks!

**Comment by zepinglee** [comment]
Does the last word ‘to’ need to be capitalized? I find `citeproc-js` (master branch, 738d51c2) produces `Test, MS., to the Stopword ‘To’`.

**Comment by adunning** [comment]
I think this is a bug in citeproc-js, but I may be missing something.

`Test, MS., to the stopword 'to'` results in `“Test, MS., to the Stopword ‘To,’” n.d.`, but `Test, MS., to the stopwords 'to' and 'and'` results in `“Test, MS., to the Stopwords ‘to’ and ‘and.’” n.d.` One of these must be incorrect.

**Comment by zepinglee** [comment]
The [spec](https://docs.citationstyles.org/en/stable/specification.html#title-case-conversion) says

> In both cases, stop words are lowercased, unless they are the first or last word in the string, or follow a colon.

but it doesn't mention the case of quoted stop word. Thus the capitalized `‘To’` seems more reasonable to me but I'm not an native English speaker after all.

**Comment by adunning** [comment]
I have checked both *The Chicago Manual of Style* and *New Hart's Rules* and cannot find anything suggesting that words in quotation marks should be capitalized differently. Let's see what the citeproc-js developers say.
