### ISSUE TITLE
Use citeproc for style development 

### ISSUE THREAD

**Issue by denismaier** [jgm/citeproc#128]
Could it be possible to use citeproc for style development? Say, use a bunch of tests and check whether the output of a given style matches the expected output.

**Comment by badumont** [comment]
I don't see it as a model, but if you read French you may grasp some ideas from my workflow here:

https://bastien-dumont.onmypc.net/git/bdumont/CSL-Clio

Note that I am not very satisfied with the test file being in HTML, for it requires to track the changes in the HTML writer and to update the test file accordingly. Using a combination of an HTML file for visualizing the result and native or json output for testing may be better.

**Comment by denismaier** [comment]
Thanks. I'll have a look into this. That looks pretty useful. I actually wanted to build something similar using [shelltestrunner](https://github.com/simonmichael/shelltestrunner), but I'm on Windows and my Haskell installation refuses to compile it... 

Anyway, I'm still thinking this could be something for citeproc to provide natively, given that it already supports citeproc-js's test format.

**Comment by denismaier** [comment]
> Note that I am not very satisfied with the test file being in HTML, for it requires to track the changes in the HTML writer and to update the test file accordingly. Using a combination of an HTML file for visualizing the result and native or json output for testing may be better.

I've now built a simple python script for this. It tests against the output of markdown-citations.

**Comment by jgm** [comment]
That seems an appropriate solution -- should we close this?

**Comment by jgm** [comment]
No, but I probably don't quite understand what you're trying to do. In any case, it doesn't sound like the kind of thing that should be built into this library.

**Comment by jgm** [comment]
This should be quite easy already using the `citeproc` executable and a little shell scripting. See its man page.

**Comment by denismaier** [comment]
Ok. Sounds reasonable. I'll have a look.

**Comment by denismaier** [comment]
How can you build the library as an executable? The readme says I should build it with the executable flag. But how?

**Comment by denismaier** [comment]
Found it:

```
stack build --flag citeproc:executable
```
