### ISSUE TITLE
Can I replace the citation key with bibliography?

### ISSUE THREAD

**Issue by endlessbeloved** [jgm/citeproc#130]
I know the citation key will be replace by the citation. and the bibliography will be listed at the end of docx.
I want to know whether could I use bibliography as the replacement. (replace the citation key with bibliography) 

one way that I solve this problem by editing the `csl` file like this: (copy the layout in bibliography element to the layout in citation element )
Is there any smart way to to do that?
Thanks!
```
  <citation et-al-min="3" et-al-use-first="1" disambiguate-add-givenname="true" disambiguate-add-year-suffix="true" collapse="year" cite-group-delimiter=", ">
    <sort>
      <key macro="author"/>
      <key macro="issued" sort="descending"/>
    </sort>
    <layout prefix="(" suffix=")" delimiter="; ">

          <the layout from bibliography element >

    </layout>
  </citation>
  <bibliography hanging-indent="true" entry-spacing="0" line-spacing="1">
    <sort>
      <key macro="author"/>
      <key macro="issued" sort="descending"/>
    </sort>
    <layout>
      <group suffix=".">
        <text macro="author" suffix=","/>
        <text macro="issued" prefix=" "/>
        <group prefix=". ">
          <text macro="title"/>
          <text macro="container"/>
          <text macro="locators"/>
        </group>
      </group>
      <text macro="access" prefix=". "/>
    </layout>
  </bibliography>
```

**Comment by jgm** [comment]
No, there's no other way -- that's the way to achieve it.

**Comment by denismaier** [comment]
Well, to wouldn't it be possible to use a filter for this?

**Comment by badumont** [comment]
I did it some day, but it is required only if one has to mix citations and full references in the main text, which seems not to be the case here. I am not entirely satisfied with my implementation, but I can share it if you are really interested.
