### ISSUE TITLE
Custom template: How to place CSLReferences at a different part of a document?

### ISSUE THREAD

**Issue by hambergerpls** [jgm/citeproc#139]
Hi,

I'm writing a custom pandoc template based on my university's thesis guidelines that will convert Markdown to PDF. The guideline requires that I need to put appendices after the Reference section. I'm very new to Latex and not sure which control sequence allows me to put the CSLReferences at a specific part of the document when using `--citeproc`.

e.g.
```tex

\begin{document}
$body$
% What control sequence? \CSLBlock , \CSLReferences \citeproc \bibliography does not work
\appendix
\input{appendix1}
\end{document}

```

**Comment by njbart** [comment]
Instructions are available here: https://pandoc.org/MANUAL.html#placement-of-the-bibliography

**Comment by hambergerpls** [comment]
Thanks for the link! @njbart 

Leaving it here for those who had the same problem.

I added the following at the top of my Markdown file

```md
---
refs: |
   ::: {#refs}
   :::
---
...
```

As for the pandoc template, 
```tex
\begin{document}
$body$
\chapter{References}
$refs$
\appendix
\input{appendix1}
\end{document}
```

We can also do this in markdown
```md
# References
   ::: {#refs}
   :::
```
