### ISSUE TITLE
How to add terms and types? (for 1.0.2)

### ISSUE THREAD

**Issue by denismaier** [jgm/citeproc#2]
Great to see that this is already so advanced.

I've just wanted to add the new variables, terms, and types we've added in 1.0.2. (1.0.2 has been [released](https://github.com/citation-style-language/schema/releases/tag/v1.0.2) just today.)

Obviously, I haven't had the time to extensively study the code, but: Am I right to assume that, unlike with variables, there's no hardcoded list of terms and types?

**Comment by jgm** [comment]
The terms are taken from the locale files.  So updating the locale files should be sufficient.

We don't currently do any validation of types, so any text string works.  (We could change that, so that a warning is emitted for unknown types?  But maybe it's not so important.)

**Comment by jgm** [comment]
Hm, I don't see any changes in the locale files (just did a pull from the repository).  Maybe I already had the latest changes. Can you inspect the locales and let me know if the new terms are there?

**Comment by jgm** [comment]
I see the locales still have `sub verbo` instead of `sub-verbo`.  But I have pulled the latest from the repositories.
Are there updated locales somewhere else?

**Comment by denismaier** [comment]
We've tagged the schema but not yet the rest of the ecosystem (styles, locales).

**Comment by denismaier** [comment]
Regarding types: I don't know if there's any need to do validation here. The validation and gate-keeping is happening at the Zotero styles repo. I don't see much value in preventing users to tweak their styles using non-spec item types.

**Comment by jgm** [comment]
OK, let me know when the new locales and styles are out, so I can update.
