### ISSUE TITLE
first-reference-number wrongly set

### ISSUE THREAD

**Issue by Dijkie85** [jgm/citeproc#21]
Every time a citation references its first occuring, it's shifted by 1. For example: 

6 H. Lane, H. Hapke, C. Howard, Natural language processing in action: Understanding, analyzing, and generating text with python, Manning Publications, 2019.
7 H. Lane, H. Hapke, C. Howard, Natural language processing in action, op. cit. **note 7**, pp. 11-16.

As you can see, it should read **op. cit. note 6**. This is happening for every reference including first-reference-number, and regardless of csl file used (tried 3 different). 

Pandoc version: 2.11.0.4
Command used: pandoc filename.md -o ../build/filename.pdf --citeproc

**Comment by jgm** [comment]
What csl style are you using?

**Comment by jgm** [comment]
I haven't been able to reproduce what you're seeing with any note styles.
Please provide a complete example so we can reproduce the issue.
You may want to use the demo here: <https://johnmacfarlane.net/citeproc/>.

**Comment by Dijkie85** [comment]
Thanks, John. I'll try to be more descriptive.
This is my the CSL I'm trying to use: http://www.zotero.org/styles/sorbonne-student-law-review.
It's a note style. I'll try others as well.

And this is a sample of the markdown I'm using:
```
En particular, en este trabajo aplicaré [@lane2019natural; @ruslan2005cl; y @beysolow2018applied.] 
... con el propósito de ... [@lane2019natural, pp. 11-16.] y finalmente ... 
[@lane2019natural, pp. 70-96.].
```

Do let me know if there is any other information I can add.

**Comment by jgm** [comment]
When I put that information into the live demo linked above, I get:

```
H. Lane, H. Hapke, C. Howard, Natural language processing in action: Understanding, analyzing, and generating text with python, Manning Publications, 2019 ; Ruslan Mitkov, The Oxford Handbook of Computational Linguistics, Oxford University Press, 2005 ; T. Beysolow, Applied natural language processing with python: Implementing machine learning and deep learning algorithms for natural language processing, Apress, 2018

H. Lane, H. Hapke, C. Howard, Natural language processing in action, op. cit. note 1, pp. 11-16

Ibid. pp. 21-33
```

That looks okay, right?

**Comment by jgm** [comment]
With pandoc (current master version and also 2.11 release) I get:
```
[1] H. Lane, H. Hapke, C. Howard, Natural language processing in action:
Understanding, analyzing, and generating text with python, Manning
Publications, 2019 ; Ruslan Mitkov, The Oxford Handbook of Computational
Linguistics, Oxford University Press, 2005 ; y T. Beysolow, Applied
natural language processing with python: Implementing machine learning
and deep learning algorithms for natural language processing, Apress,
2018.

[2] H. Lane, H. Hapke, C. Howard, Natural language processing in action,
op. cit. note 1, pp. 11-16.

[3] Ibid. pp. 70-96.
```
Also looks ok.

**Comment by Dijkie85** [comment]
It does look ok. I don't know what could be wrong with my setup then. Thanks for looking into this.

**Comment by Dijkie85** [comment]
In case it's relevant, I'm using "ES" locale...

**Comment by jgm** [comment]
Using ES locale didn't make a difference to my tests.
I guess I'll close this, then, but feel free to post again if you can find a test case that I can use to reproduce the issue, and I'll re-open it.
