### ISSUE TITLE
Add an option --no-citationmark-relocation

### ISSUE THREAD

**Issue by badumont** [jgm/citeproc#34]
First and foremost, thank you very much for all your work. Scholarly writing became much more fluid since I discovered pandoc. 

The issue I experiment is similar to #6 in that it is related with the diversity of conventions about the localisation of footnote marks between languages. As a French, my problem is that I would need the mark to be *before* the punctuation marks. The strange thing is that I didn't have it with `pandoc-citeproc`, as the footnote marks stayed where I placed my citations in the `md` file.

Although we could write lua filters to move the footnote marks after citeproc processing to match the pattern of the targeted languages, the simplest way to handle this may be to add an option that inhibits the mark/punctuation moving mechanism. Do you think that it could be feasible? After all, this is how regular footnotes work in pandoc.

**Comment by jgm** [comment]
Did you see the section of the pandoc manual about setting
```
notes-after-punctuation
```
in the metadata?

Try setting this to `false`.

**Comment by badumont** [comment]
Oh, I'm stupid and sorry. I did check the manual, but I stopped just before that point because I thought it had switched to questions specific to the bibliography... Thank you very much!

**Comment by jgm** [comment]
Great, let me know if it doesn't work.
