### ISSUE TITLE
Treatment of unknown variables / non-strict mode

### ISSUE THREAD

**Issue by denismaier** [jgm/citeproc#4]
Currently, this library ignores unknown variables. Citeproc-js just treats them as string variables. While that probably should not be the default, what about a non-strict mode where unknown variables are just treated as string variables?

**Comment by jgm** [comment]
I think could probably just treat them as string variables by default.  I don't see what harm that would do.

**Comment by denismaier** [comment]
> I think could probably just treat them as string variables by default. I don't see what harm that would do.

Yeah, probably should be ok. If the catch-all pattern is just `variableType _ = StringVariable`, would there still be the need to define string variables explicitly? Technically not, of course, but is there some value in doing it nevertheless?

**Comment by jgm** [comment]
It's probably worth keeping the explicit definitions in there, in case we decide to go back to treating unknown variables differently.
