### ISSUE TITLE
Why does punctuation move to inside quotes?

### ISSUE THREAD

**Issue by holmescharles** [jgm/citeproc#46]
What I did:

```sh
echo 'Lorem "ipsum".' | pandoc -t html -o - --citeproc
```

Output:
```
<p>Lorem “ipsum.”</p>
```

Now let's make sure this is caused by citeproc:

```sh
echo 'Lorem "ipsum".' | pandoc -t html -o -
```

Output:
```
<p>Lorem “ipsum”.</p>
```

Why did the period move to inside the quotes? There are not citations at the end of the sentence, so why change anything?

**My real question:** How do I tell citeproc to not do this (i.e., move the punctuation)?

**Comment by jgm** [comment]
> My real question: How do I tell citeproc to not do this (i.e., move the punctuation)?

This is locale-dependent.
The default locale (en-US) has
```
  <style-options punctuation-in-quote="true"/>
```
If you try adding `lang: en-GB` to your metadata, for example, you'll see different behavior.
Alternatively you could add the following to the `<locale>` section of your CSL style:
```
  <style-options punctuation-in-quote="false"/>
```
