### ISSUE TITLE
Missing delimiter between year and disambiguation character

### ISSUE THREAD

**Issue by Tajnymag** [jgm/citeproc#47]
I'm finishing up my thesis and I find the generated citation format rather odd.

Rendered citation
![obrazek](https://user-images.githubusercontent.com/3985946/105500915-dd882f80-5cc3-11eb-8157-6b338419653e.png)

Rendered bibliography
![obrazek](https://user-images.githubusercontent.com/3985946/105500863-cba68c80-5cc3-11eb-9382-7f649c4074ad.png)

When the reference date is missing and there's multiple bibliography entries with the same Author, the "no date" is rendered as "no datea"/"no dateb" and so on. The character used for disambiguation should be delimited somehow. With years it makes sense but witout the year, it looks like a typo.

Is there any workaround I could use to put a space or a semicolon there? To get `(SAP, nedatováno;a)` instead?

**Comment by jgm** [comment]
I think I'll change this so that a space is inserted if the "long" form of the "no date" term is used.

**Comment by Tajnymag** [comment]
@jgm Wonderful! Thank you so much!
