### ISSUE TITLE
Can't find CSL in ~/.csl directory *or* follow relative paths to CSL files.  

### ISSUE THREAD

**Issue by paultopia** [jgm/citeproc#50]
hi there!  So [this very old issue](https://github.com/jgm/pandoc/issues/3212) for the previous pandoc-citeproc filter suggests that that earlier iteration looked in ~/.csl for style files. 

I currently have a ~/.csl directory sitting around containing all 2000-some CSL styles from the central CSL repository.  Including, importantly, `chicago-author-date.csl`.  But I can't for the life of me figure out how to actually get citeproc to find that repository. 

I started with a defaults file in ~/.pandoc/defaults/research.yaml that contains, in relevant part, 

```
citeproc: true
csl: chicago-author-date
```

but running `pandoc -o testres.pdf --defaults=research markdown.md` yields the error `File chicago-author-date.csl not found in resource path.`

Then I changed it to a full relative pathname: `csl: ~/.csl/chicago-author-date.csl`

But, same error.  

Finally, I gave it a full absolute path, i.e., `csl: /Users/myhome/.csl/chicago-author-date.csl` and that worked.  

Similar errors happen passing relative paths directly from the commandline rather than in a defaults file.
 
I'm using Pandoc 2.11.4 (installed via homebrew on on Macos catalina, if it matters).

**Comment by jgm** [comment]
citeproc doesn't look in .csl any more, as documented in the changelog for pandoc 2.11:

  - pandoc-citeproc searches the `~/.csl` directory for `.csl`  styles.  Pandoc instead searches the `csl` subdirectory of the pandoc user data directory (e.g., `~/.pandoc/csl` or  `~/.local/share/pandoc/csl`).  Users who already keep CSL styles in `~/.csl` may find it convenient to add a symlink.

**Comment by paultopia** [comment]
Aaah thank you.  Is the relative pathname thing also intended behavior?

**Comment by jgm** [comment]
Tilde expansion is a shell feature.  If you specify a tilde on the command line, the shell will interpret it as your home directory before it is passed on to pandoc.  But if you specify a tilde in metadata within your file, it's not interpreted by the shell so it's just...a tilde.

But your question does come up quite a bit, e.g.
https://github.com/jgm/pandoc/issues/5977
https://github.com/jgm/pandoc/issues/3135
A case could be made for expanding tildes in these contexts, I suppose.
