### ISSUE TITLE
Weird comma in front of the page using DIN1505

### ISSUE THREAD

**Issue by MAWSpitau** [jgm/citeproc#56]
Hi there, 

- I am using the https://github.com/citation-style-language/styles/blob/master/din-1505-2.csl for my citations.
- I always get a wierd comma in front of my year and I have no idea how to get rid of it

the citation in the markdownfile (in an footnote):
` [^3f261b3e]: @Spitau2019`

the bibtex entry
```
@Book{Spitau2019,
author    = {Spitau, Marcel},
title     = {Papier Im Griff - Vom Informationsbesitzer Zum Informationsbenutzer Mit Classei},
publisher = {Independently Published},
isbn      = {978-1-092-11316-8},
address   = {Printed in the United States of America},
year      = {2019},
}
```
And this is how it looks like... 
https://i.imgur.com/RYI68U0.png

I do not understand WHY there is the comma and I want to get rid of it.

Any ideas?

```
pandoc 2.11.3
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
```
This is my commandline to get an PDF:
```
pandoc md-Mein-Buch.md -s --bibliography /home/marcel/Dropbox/1_arbeit/zettelkasten/literatur.bib --pdf-engine=xelatex --citeproc --csl /home/marcel/.pandoc/din-1505-2.csl -o pdf-Mein-Buch.pdf
```

**Comment by denismaier** [comment]
Not related to you bug, but your title casing of a German title is incorrect.

Von: MAWSpitau <notifications@github.com>
Gesendet: Montag, 22. Februar 2021 11:09
An: jgm/citeproc <citeproc@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [jgm/citeproc] Weird comma in front of the page using DIN1505 (#56)


Hi there,

  *   I am using the https://github.com/citation-style-language/styles/blob/master/din-1505-2.csl for my citations.
  *   I always get a wierd comma in front of my year and I have no idea how to get rid of it

the citation in the markdownfile (in an footnote):
[^3f261b3e]: @Spitau2019

the bibtex entry

@Book{Spitau2019,

author    = {Spitau, Marcel},

title     = {Papier Im Griff - Vom Informationsbesitzer Zum Informationsbenutzer Mit Classei},

publisher = {Independently Published},

isbn      = {978-1-092-11316-8},

address   = {Printed in the United States of America},

year      = {2019},

}

And this is how it looks like...
https://i.imgur.com/RYI68U0.png

I do not understand WHY there is the comma and I want to get rid of it.

Any ideas?

pandoc 2.11.3

Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,

citeproc 0.3.0.3, ipynb 0.1.0.1

This is my commandline to get an PDF:

pandoc md-Mein-Buch.md -s --bibliography /home/marcel/Dropbox/1_arbeit/zettelkasten/literatur.bib --pdf-engine=xelatex --citeproc --csl /home/marcel/.pandoc/din-1505-2.csl -o pdf-Mein-Buch.pdf

-

**Comment by MAWSpitau** [comment]
Hey, thanks. I will change that. I am wondering, where that came from? Maybe jabref is screwing it up...

**Comment by jgm** [comment]
Try using
```
 [@Spitau2019]
```
instead of
```
 @Spitau2019
````
When you use an author-name-in-text form like the latter, in the context of a footnote, pandoc inserts a comma between the author's name and the rest.  Generally that produces good results, but here's a case where it doesn't, because of the extra formatting added by the style.  I think you'll avoid the whole issue though if you just use the bracketed form.

**Comment by MAWSpitau** [comment]
Hey, thanks. That is not exactly what I wanted, but a good workaround. 

Solutions:
1. Using the brackets **[ ]**, but having **( )** in the rendered file.
2. Searching for an other cls - file. 

Thanks for helping me out.
