### ISSUE TITLE
Regression: --csl= relative path is ignored when specifying --resource-path=

### ISSUE THREAD

**Issue by stroobandt** [jgm/citeproc#58]
~~~
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
~~~

The following used to work flawlessly with `pandoc 2.5` (which used `pandoc-citeproc`):

```bash
$ pandoc --resource-path=figures --csl=styles/american-medical-association.csl …
```
In other words, I created two subdirectories under my current working directory `./figures/` and `./styles/`. The `figures` directory is assigned to the `resource-path` and the `--csl=` option points to a relative file path. Nonetheless, with `pandoc 2.11.4` (which uses now `citeproc` instead of `pandoc-citeproc`) this results in the following error:

```
File styles/american-medical-association.csl not found in resource path
```
This is [not according to the manual](https://pandoc.org/MANUAL.html#option--csl), which states:

> If FILE is not found relative to the working directory, it will be sought in the resource path (see `--resource-path`) and finally in the `csl` subdirectory of the pandoc user data directory.

**Comment by jgm** [comment]
Look at the documentation for `--resource-path`.  If you set a resource path, you  must explicitly include the working directory `.` if you want it to be searched.
