### ISSUE TITLE
Font size for citations

### ISSUE THREAD

**Issue by dhicks** [jgm/citeproc#59]
I'm transitioning from LaTeX to R Markdown (and so Pandoc and so citeproc) to write Beamer slides.  I'm the kind of academic who uses lots of citations, including as in-line author-date citations on my slides.  To reduce visual clutter, I then set the font of the in-line citations as small as possible, eg, `\tiny`.  I'm trying to figure out whether this is possible in my new workflow.  

I've looked into whether a custom CSL style would work.  However, in [this Zotero thread from 2008](https://forums.zotero.org/discussion/4814/font-size-of-author-date-citations-in-footnotes), a CSL developer indicates that CSL doesn't support font size styling, arguing that it should be handled downstream so that it matches the surrounding document.  I haven't been able to find any more recent discussions of font size and CSL. 

My next idea was to check out how citations are represented in the TeX file; if they're getting turned into `\cite` commands or some such, then maybe I could put a wrapper around that command in the preamble.  (This is basically what I did with the biblatex commands when I wrote the LaTeX directly.)  But it appears the citations just become plain text strings.  

So is there any way I can intervene between the CSL styling and the generated TeX file to get something whose font size I can control?

**Comment by badumont** [comment]
Simply run this as a Lua filter:

function Cite(citation)
   return { pandoc.RawInline('latex', '{\\tiny '), citation, pandoc.RawInline('latex', '}') }
end
