### ISSUE TITLE
Citeproc doesn't support et-al-subsequent-use-first

### ISSUE THREAD

**Issue by mirh** [jgm/citeproc#60]
I mean, I know for sure the "et-al" abbreviations criteria are nowhere to be found, but I would guess other exist. 

To reproduce, just use the [6th ed. APA style](https://github.com/jgm/pandoc/blob/master/test/command/apa.csl) and try to cite the same multi-author reference twice. 
Then convert from markdown to latex and `et-al-subsequent-use-first="1"` should make it so the second time you only get "dude et. all". 
Starting with pandoc 2.11 though, they are always and forever named in long form.

**Comment by jgm** [comment]
Looking at the code, it seems indeed that although we parse the `et-al-subsequent` attributes in the style, we don't do anything with them in Eval.hs.

**Comment by mirh** [comment]
Hoping you also checked if other stuff wasn't missing, thank you.
