### ISSUE TITLE
Can support for bibtex's "and others" be improved?

### ISSUE THREAD

**Issue by tarleb** [jgm/citeproc#61]
BibTeX allows to use the special string `and others` in author names, which is rendered as "et al.". Pandoc's bibtex parser already treats this specially

```haskell
toName _ [Str "others"] =
  return emptyName{ nameLiteral = Just "others" }
```

while citeproc seems to treat that name just as any other. Is it possible (and sensible) to mirror bibtex's behavior here? If so, where would be a good place to put the code?

For reference: this issue is motivated by openjournals/joss-reviews#3000.

**Comment by jgm** [comment]
I wonder if we could do something as simple as handling an `emptyName { nameLiteral = Just "others" }` in citeproc by looking up the "and others" term?  (We'd have to decide on long or short form.) I have some qualms about this idea, because it would be departing from the CSL standard, but it probably wouldn't break anything.

**Comment by denismaier** [comment]
Well, yes that departs from the CSL standard, but I think that would be a reasonable compromise given the prevalence of these special strings in bibtex/biblatex files databases.
Maybe pandoc should emit a warning when this happens? And perhaps there could be a strict mode where this even leads to errors?

**Comment by jgm** [comment]
The problem with my proposal above is that CSL will already add the "and" before the last name in a list in a bibliography.  We don't want:

> Smith, John, Sarah Song, and et al.

But I think we can make it work.  In `Citeproc.Eval.formatNames`, we can look to see if the last name is this `others` literal; if it is, we can set the et al threshold to just before the last name.
