### ISSUE TITLE
Suppress author name

### ISSUE THREAD

**Issue by whrose** [jgm/citeproc#62]
Before the new citeproc protocol one was able to suppress the author name of a citation by adding a dash before the bibliography entry, e.g., `-@Smith04`. With the new protocol this ends up in LaTeX as: -Smith (2004). Is this a bug?

**Comment by jgm** [comment]
See jgm/pandoc#7219
(duplicate)

**Comment by whrose** [comment]
My apologies, I should have seen that. Sorry for wasting
your time.

I do hope you will restore the old behaviour. A lot of
author names in a language like Dutch have a prefix
like ‘de‘ or ‘van‘, which sometimes need a capital
and sometimes not. If I use markdown inline footnotes
square brackets cannot be used for this new behaviour,
as far as I understand. But maybe I should not use
inline footnotes.

Kind greetings,

Wolter

**Comment by jgm** [comment]
> If I use markdown inline footnotes square brackets cannot be used for this new behaviour, as far as I understand.

Can you elaborate?  I'm not sure I understand.  You should be able to use `[-@citekey]` to the same effect as `-@citekey`; as far as I can see they will do exactly the same thing.  And yes, nested brackets inside an inline note are okay.

**Comment by whrose** [comment]
I stand corrected. I should have tested first, before I wrote my previous
email.
I now see that nested brackets do not cause a problem. Apologies, again.


Kind greetings,

Wolter
