### ISSUE TITLE
Is there something equivalent to "\bibentry" (from LaTeX) in citeproc?

### ISSUE THREAD

**Issue by firasm** [jgm/citeproc#64]
Hello! Thanks for working on this great package/utility.

I am trying to build my CV in markdown but keeping citations and references in a .bib file. 

I have a bit of a mixed-use case where I want to have the full bibliographic record in the middle of the document, separate from the bibliography. It is fine if those records also show up in the bibliography. Here is an image of what I am trying to achieve.

In regular latex, I can do this using `\bibentry{cite-key}` , from the `natbib` package like so:

![bibentry_result_example](https://user-images.githubusercontent.com/2507459/115135094-81832d80-9fca-11eb-917b-2dfe88201b25.png)

## Minimum working example

I've set up a [minimum working example](https://github.com/firasm/demo_citeproc) here in a GitHub repo. I convert to pdf with the following incantation:

```
pandoc --bibliography bibliography.bib -o test.pdf test.md  --citeproc
```

<img width="636" alt="Screen Shot 2021-04-17 at 10 12 46 PM" src="https://user-images.githubusercontent.com/2507459/115135065-56004300-9fca-11eb-84ea-3ef57fbfff3b.png">

I can specify a different style by adding: `--csl bioethics.csl` to turn those into numeric references rather than author-name, but that won't solve my immediate problem of adding the entries in the middle of my document.

Thanks in advance for any help you can provide!

**Comment by jgm** [comment]
It's possible to create a custom csl file that simply formats citations the same way it does bibliography entries.

**Comment by firasm** [comment]
Right, of course! Thanks for pointing me in that direction. Turns out there is a csl file that does almost what I need that I can edit: [APA-CV](https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa-cv).

Thanks again.
