### ISSUE TITLE
Recommeded way for bib2yaml functionality

### ISSUE THREAD

**Issue by nsheff** [jgm/citeproc#65]
The old `pandoc-citeproc` package had a 'convert' mode with `--bib2yaml` that would convert a bibtex file into a yaml file suitable for use as frontmatter with pandoc.

With deprecation of `pandoc-citeproc` and the move to this `citeproc` package, what is now the recommended way to convert a bibtex file into yaml?

**Comment by denismaier** [comment]
From the pandoc manual:

> Note that pandoc can be used to produce such a YAML metadata section from a BibTeX, BibLaTeX, or CSL JSON bibliography:
> 
> ```
> pandoc chem.bib -s -f biblatex -t markdown
> pandoc chem.json -s -f csljson -t markdown
> ```
> 
> Indeed, pandoc can convert between any of these citation formats:
> 
> ```
> pandoc chem.bib -s -f biblatex -t csljson
> pandoc chem.yaml -s -f markdown -t biblatex
> ```

**Comment by nsheff** [comment]
Thanks, I don't know why that didn't come up in my searches, it works.

For future searchers, this is fine, but it didn't work for my use case because I wanted to use some custom fields in my `.bib` file, which are not exported by pandoc. I ended up solving the problem by writing a custom export formatter and then using JabRef to spit out a yaml with all the fields I needed.
