### ISSUE TITLE
0.4 doesn't build with -f icu

### ISSUE THREAD

**Issue by felixonmars** [jgm/citeproc#71]
`Text.Collate.Lang` was imported regardless of the flag, but the library is only required when -f icu is not specified.

```
[ 2 of 11] Compiling Citeproc.Unicode

src/Citeproc/Unicode.hs:13:1: error:
    Could not find module ‘Text.Collate.Lang’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
13 | import Text.Collate.Lang (Lang(..), parseLang, renderLang, lookupLang)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jgm** [comment]
I think we need this module; the solution is to make unicode-collation an unconditional build-depend. I'll do that.

**Comment by jgm** [comment]
I thought we were checking the icu build in CI; also need to look into that!
