### ISSUE TITLE
No citation is output

### ISSUE THREAD

**Issue by kanata25** [jgm/citeproc#76]
When I converted LaTeX to JATS with the latest Pandoc, no citations are output.

`pandoc --from=latex --to=jats --bibliography="test.bib" "test.tex" --verbose > ./test.xml`

The following message is displayed. Do you know what the cause is?

```
pandoc --from=latex --to=jats --bibliography="test.bib" "test.tex"  --verbose > ./test.xml
[INFO] Not rendering RawInline (Format "latex") "\\cite{B1}"
```

The version of Pandoc is as follows.

```
pandoc --version
pandoc.exe 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, ipynb 0.1.0.1
```

If you switch back to Pandoc 2.10, it will be output.
The Pandoc result is as follows.

```
pandoc --from=latex --to=jats --bibliography="test.bib" "test.tex" --verbose > ./test.xml
[INFO] Running filter pandoc-citeproc
[INFO] Completed filter pandoc-citeproc in 31 ms
```

test.tex
```
\documentclass[dvipdfmx]{article}
\begin{document}
\section{Citation}
Citation sample \cite{B1}
\bibliography{test}
\end{document}
```

test.bib
```
@article{B1,
  title = "A Sample of JATS Extraction",
  author = "test",
  journal = "Sample",
  year = "2020",
  month = "apr",
  volume = "1",
  number = "2",
  pages = "123--456"}
```

**Comment by kanata25** [comment]
It will be registered on the Pandoc side, so close it.

**Comment by jgm** [comment]
Try adding `--citeproc`.

**Comment by kanata25** [comment]
Thank you for your comment.
By adding --citeproc, , I was able to output as expected.

I'm sorry to hear that simple thing. Thank you for your support.
