### ISSUE TITLE
link-citations:true author and year have two distinct hyperlinks

### ISSUE THREAD

**Issue by perrette** [jgm/citeproc#77]
Using the same example as in #74, but adding link-citations:true, I encounter an unexpected behaviour:

- article.md:
`This is a work by @gosling2017isimip2a.`
- bibliography.md:
```
@article{gosling2017isimip2a,
  title={ISIMIP2a simulation data from water (global) sector},
  author={Gosling, S and M{\"u}ller Schmied, H and Betts, R and Chang, J and Ciais, P and Dankers, R and D{\"o}ll, P and Eisner, S and Fl{\"o}rke, M and Gerten, D and others},
  journal={GFZ Data Services},
  year={2017}
}
```
- command: `pandoc --citeproc article.md --bibliography bibliography.bib --metadata link-citations=true`
- output:
```html
<p>This is a work by <span class="citation" data-cites="gosling2017isimip2a"><a href="#ref-gosling2017isimip2a" role="doc-biblioref">Gosling et al.</a> (<a href="#ref-gosling2017isimip2a" role="doc-biblioref">2017</a>)</span>.</p>
<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-gosling2017isimip2a" class="csl-entry" role="doc-biblioentry">
Gosling, S, H Müller Schmied, R Betts, J Chang, P Ciais, R Dankers, P Döll, et al. 2017. <span>“ISIMIP2a Simulation Data from Water (Global) Sector.”</span> <em>GFZ Data Services</em>.
</div>
</div>
```

- What's going wrong (?): there are two href elements (author and date), where I would have expected only one.

- `pandoc --version`
> pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1

**Comment by jgm** [comment]
This is because citeproc itself doesn't have a notion of an author-in-text citation.
We simulate that by combining two citations, one author-only and one suppress-author.
Hence the two hyperlinks.
This might change in the future, since CSL is codifying something about author-in-text citations.

**Comment by jgm** [comment]
Probably we should simply omit the hyperlink on the author-only part.

**Comment by perrette** [comment]
And does pandoc does something else on top of citeproc tben? What brought me here is that in a larger setup which I don't have the full overview, the full `author (year)` comes up as a unique link after pandoc conversion, whereas a reference inside a figure caption has the same two-links pattern pointed out in this issue. That behaviour is puzzling to me. Maybe that's an issue for pandoc this time?

**Comment by jgm** [comment]
No, pandoc had the double links too, for *author-in-text citations*.
(This is changed now, in the latest commit.)
For regular citations, you don't get them.
```
@smith2000 gets a double link.
[@smith2000] does not.
```

**Comment by perrette** [comment]
I see, thanks.

**Comment by TomBener** [comment]
> No, pandoc had the double links too, for _author-in-text citations_. (This is changed now, in the latest commit.) For regular citations, you don't get them.
> 
> ```
> @smith2000 gets a double link.
> [@smith2000] does not.
> ```

I tried to convert Markdown to docx with Pandoc 2.19.1 and citeproc 0.8.0.1.

Markdown example:

```markdown
@smith2000 will be rendered as only one hyperlink. While both the author and date of ([@smith2000]) are hyperlinked.
```

run:

```shell
pandoc -C main.md --bibliography bibliography.bib -M link-citations=true -o main.docx
```

The author-in-text citation like `@smith2000` will be rendered as only one hyperlink. Only the year is hyperlinked.

<img width="855" alt="CleanShot 2022-08-22 at 17 45 44@2x" src="https://user-images.githubusercontent.com/49151155/185892173-a6ddfd4e-b5ae-4b77-811b-172f43681196.png">

Does Pandoc has an option to hyperlink both the author and year for author-in-text citations?
