### ISSUE TITLE
Question: is it possible to use Citeproc with backref?

### ISSUE THREAD

**Issue by bcdavasconcelos** [jgm/citeproc#78]
Hello John,
is it possible to use backref with Citeproc (in the MD to LaTeX/PDF conversion)? I found [a request for this](https://pandoc-discuss.narkive.com/p47XF7O1/citeproc-and-pandoc-bibliographies) and [a reply saying that it should be possible](https://github.com/jgm/pandoc-citeproc/issues/56#issuecomment-98921275), but couldn't find anything in the documentation or any way to do it.

EDIT: It just occurred to me that the request was probably for hyperref links between the citation and the reference, and that the backref was just mentioned _en passant_. Still, I am curious if this could be achieved (that is, inserting hyperpageref for each entry back to the text).

**Comment by jgm** [comment]
I don't know what you mean by backref here.  Do you mean that bibliography entries should link back to the part of the text that cites them?  Of course, there may be many parts of the text that cite them.

Anyway, no, this isn't possible with citeproc.  If you're targeting PDF, you may want to use the `--biblatex` option, which can make this possible.  (You'd then need to use pandoc to create tex and compile it separately, or use `--pdf-engine=latexmk` with appropriate options.)

**Comment by bcdavasconcelos** [comment]
Thanks for getting back to me.

By backref I mean what can be achieved with `\usepackage[backend=biber, backref=true]{biblatex}` in biblatex. This prints out, after each entry in the bibliography, the page numbers of where the reference occurs ([example](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftex.stackexchange.com%2Fquestions%2F36307%2Fformatting-back-references-in-bibliography&psig=AOvVaw0npxIPCJxtcXjesuUxaWEp&ust=1625265293322000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCPDv15b3wvECFQAAAAAdAAAAABAD)).

If this is could be achieve via Pandoc, it would be very interesting.

**Comment by jgm** [comment]
No, it can't, sorry.
