### ISSUE TITLE
`link-citations: false` does not disable the hypertargets in the bibliography

### ISSUE THREAD

**Issue by Armavica** [jgm/citeproc#85]
Hello,
Is there a reason to keep the hypertargets in the bibliography when `link-citations` is disabled?

**Comment by jgm** [comment]
`link-citations` is *only* about linking citations to the corresponding bibliography items.
Hyperlinking URLs in the bibliography is a separate issue.

**Comment by Armavica** [comment]
Sorry if my question was not clear, here is a minimal example:
``` markdown
---
title: Test
references:
- id: pasteur
  author:
  - family: Pasteur
    given: Louis
  title: 'Mémoire sur la fermentation acétique'
  issued: 1864
---

This is a test [@pasteur].

# References
```
Compiled with `pandoc test.md --citeproc -o test.tex` gives
``` tex
This is a test (\protect\hyperlink{ref-pasteur}{Pasteur 1864}). % with link-citations
This is a test (Pasteur 1864). % without link-citations

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-pasteur}{}} % with or without link-citations
Pasteur, Louis. 1864. {``Mémoire Sur La Fermentation Acétique.''}

\end{CSLReferences}
```
I wonder why the line in the reference with the hypertarget to `ref-pasteur` remains even when `link-citations` is set to false.

**Comment by jgm** [comment]
Does the hypertarget do any harm?
Pandoc always generates hypertargets for Divs with id attributes.

**Comment by Armavica** [comment]
I am trying to generate a tex file from markdown for an editor whose LaTeX template forbids the use of any package, so I cannot have any `hypertarget` in the file. To remove them from the sections I use `-f markdown-auto_identifiers`, so I was hoping that the `link-citations` flag would remove them also from the reference list.

**Comment by jgm** [comment]
Well, you can just include-in-header somthing like
```
\newcommand{\hypertarget}[2]{}
```

**Comment by Armavica** [comment]
My understanding is that they never compile the LaTeX file, they translate it into HTML with a custom script. So I am not sure that this will work…

**Comment by jgm** [comment]
That's maddening, since you could simply convert the markdown to HTML directly!
Well, I'd suggest using sed or perl to postprocess, in that case. I'm not going to change the way pandoc works just because of one editor's workflow.

**Comment by Armavica** [comment]
I understand, thank you for your time anyway.

**Comment by jgm** [comment]
I'm going to reopen this, because I'm now thinking that it could be useful to make *both* links from citations to the bibliography and hyperlinks from the bibliography to be conditional on the `link-citations` option.

Are there situations where one would want to control these independently?

**Comment by jgm** [comment]
Links in bibliography can now be controlled independently using `link-bibliography`. Closing.
