### ISSUE TITLE
Support CSL Recommendation for Linked Titles

### ISSUE THREAD

**Issue by benrbray** [jgm/citeproc#86]
(originally posted on [pandoc-discuss](https://groups.google.com/g/pandoc-discuss/c/eWBslDyLGQc))

The CSL specification has a [recommendation for automatically linking titles](https://github.com/citation-style-language/documentation/blob/master/specification.rst#appendix-vi-links) when the citation style does not explicitly render the URL.  See also [this discussion on GitHub](https://github.com/citation-style-language/documentation/issues/76).

**How hard would it be for `citeproc` / `pandoc` to support this recommendation, at least for the `pandoc` HTML writer?  Would this be a desirable change?**

I poked a round a bit in the `pandoc` source (for instance [here](https://github.com/jgm/pandoc/blob/407de98b5e3971c84c7e89de5f2a9d317b4d4557/src/Text/Pandoc/Writers/HTML.hs#L813-L853)), but it wasn't clear to me where I might hook in to add this functionality.  If this is a desirable change, I might be able to put together a PR.  Some tips about how to get started on this would be appreciated!

My use case is Hakyll, where I want to use Pandoc to generate a bibliography, but I want a hyperlinked title instead of raw URLs.  I could hack something together to modify the HTML manually, but since there's an official CSL recommendation, it might be a nice feature to have in Pandoc itself.

### Relevant Snippet from CSL Spec

> The CSL syntax does not have support for configuration of links. However, processors should include links on bibliographic references, using the following rules:
>
> If the bibliography entry for an item renders any of the following identifiers, the identifier should be anchored as a link, with the target of the link as follows:
>
> 1. ``url``: output as is
> 2. ``doi``: prepend with "https://doi.org/"
> 3. ``pmid``: prepend with "https://www.ncbi.nlm.nih.gov/pubmed/"
> 4. ``pmcid``: prepend with "https://www.ncbi.nlm.nih.gov/pmc/articles/"
>
> If the identifier is rendered as a URI, include rendered URI components (e.g. "https://doi.org/") in the link anchor. Do not include any other affix text in the link anchor (e.g. "Available from: ", "doi: ", "PMID: ").
> If the bibliography entry for an item does not render any of the above identifiers, then set the anchor of the link as the item ``title``. If ``title`` is not rendered, then set the anchor of the link as the full bibliography entry for the item. Set the target of the link as one of the following, in order of priority:
> 
> 1. ``doi``: prepend with "https://doi.org/"
> 2. ``pmcid``: prepend with "https://www.ncbi.nlm.nih.gov/pmc/articles/"
> 3. ``pmid``: prepend with "https://www.ncbi.nlm.nih.gov/pubmed/"
> 4. ``url``: output as is
> 
> If the item data does not include any of the above identifiers, do not include a link.
> 
> Citation processors should include an option flag for calling applications to disable bibliography linking behavior.

**Comment by njbart** [comment]
FWIW, these "recommendations" are from the draft of the upcoming 1.0.2 version of the CSL specs, AFAIK still work in progress. They are not part of the current 1.0.1 specs (see https://docs.citationstyles.org/en/stable/ and https://github.com/citation-style-language/documentation/releases). That being said, it’d be a nice feature, and I’m certainly not against it being implemented.

**Comment by jgm** [comment]
That explains why I didn't notice them before!

**Comment by jgm** [comment]
Note: currently we linkify DOI, URL, ISBN, PMCID, PMID in pandoc itself (T.P.Citeproc, linkifyVariables).  But I think that, to implement this suggestion properly, we'd need to move all of this into citeproc.  (Pandoc won't have the information it needs about whether the style has rendered a URL field already, and which part of the rendered text is the title.)

Possible road map to implement this:

- Add TagTitle constructor to Tag, so we can keep track of the title.
- Add something to EvalState that tracks whether we've rendered a doi, pmcid, pmid, or url field.
- Use addHyperlink to link these when we add them, in accordance with the instructions above.
- After rendering the bibliography entry, check this state field, and, if no URL has been rendered already and the bibliographic data includes one, hyperlink the title (locating it using the Tag).  If there's no title, hyperlink the whole thing.

**Comment by jgm** [comment]
Note that pandoc currently hyperlinks ISBN too, but this isn't in the recommendation above.
