### ISSUE TITLE
Prevent sorting of citations with prefixes

### ISSUE THREAD

**Issue by jdhauck** [jgm/citeproc#89]
For styles that sort citations, it should be possible to prevent sorting for those cases when citations have prefixes, such as the following: 

`[@Heller:2007i, 10; see also @Gal:1987; @Heller:1989]`

Currently it produces with CMS Author Date:  `(Heller 2007, 10, 1989; see also Gal 1987)` 
It should produce:  `(Heller 2007, 10; see also Gal 1987; Heller 1989)`

Following up from the discussion [here](https://groups.google.com/g/pandoc-discuss/c/jNWLsRdRKrY) 

A fix for this issue has been implemented a few years ago in `pandoc-citeproc`:
https://github.com/jgm/pandoc-citeproc/commit/31b463a939d4878d4c83c318976b66d723e70bf5
see issue here: https://github.com/jgm/pandoc-citeproc/issues/292

But it is not in CSL. 
Can this be implemented?

**Comment by jgm** [comment]
Now that I look at the citeproc code, I see that there is code here that seems intended to deal with this:
```hs
      -- We can't just sort all the citations, because
      -- this can make a hash out of prefixes and suffixes.
      -- See e.g. pandoc-citeproc issue #292.
      -- we need to first break into groups so that any
      -- suffix ends a group and any prefix begins a group;
      -- then sort the groups; then combine again:
      let canGroup i1 i2
           =   isNothing (citationItemSuffix i1) &&
               isNothing (citationItemPrefix i2)
      let sortCitationItems citation' =
            citation'{ citationItems =
                          concatMap
                           (sortBy
                             (\item1 item2 ->
                               collate
                                (fromMaybe [] $ M.lookup
                                   (citationItemId item1) sortKeyMap)
                                (fromMaybe [] $ M.lookup
                                   (citationItemId item2) sortKeyMap)))
                        $ groupBy canGroup
                        $ citationItems citation' }
```

**Comment by jgm** [comment]
OK, I see what is happening.
citeproc *is* implementing the split-into-groups-and-sort-each-group algorithm described in the comment.  But this isn't working in the case where a citation before the prefix and acitation after the prefix get collapsed.

**Comment by jgm** [comment]
Perhaps it will suffice to add a condition on collapsing so that items with prefixes/suffixes don't get collapsed.
