### ISSUE TITLE
Integration into other Programs?

### ISSUE THREAD

**Issue by iandol** [jgm/citeproc#9]
I was wondering if a longer term goal was to allow your citeproc library to be used from other applications? Current citeproc variants are not so easy to embed into other apps as they depend on a JS engine or Java etc. Sorry for my absolute ignorance, but can Haskell libraries be interfaced to programs written in other languages, and what would be required to do so?

Thank you!

**Comment by jgm** [comment]
It would not be hard at all to create a standalone binary that acts as a pipe, taking as input a JSON structure with the CSL, bibliographic items, and citations, and yielding as output another JSON with formatted bibliography and citations.

It is also possible to create a dynamic library that can be called from C.
See 6.12.2 at https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/shared_libs.html?highlight=dylib

Also: https://www.well-typed.com/blog/2009/05/buildings-plugins-as-haskell-shared-libs/

This requires building an interface between the Haskell and C types.

A third option would be to create an executable server that can receive requests and respond with formatted citations.

**Comment by denismaier** [comment]
I've recently heard it should be possible to compile Haskell to web assembly. Depending on context that could also be helpful. Don't know how mature that is.

**Comment by iandol** [comment]
I was prompted to ask this as writing apps like Scrivener would benefit from being able to include citeproc functionality: https://www.literatureandlatte.com/forum/viewtopic.php?f=4&t=51779 — this is written in objective-c on macOS. Current citeproc engines are not really designed for use in other programs. There is https://github.com/cormacrelf/citeproc-rs — but this is still in the development phase. It seems @jgm has done a great job of creating a new engine, with better potential of embedding in another app compared to e.g. citeproc-js...

It sounds as if the JSON pipe is the most direct solution for the moment; other options seem to require quite a bit of scaffolding on both sides...

**Comment by jgm** [comment]
JSON pipe would be easy to provide -- probably best done through a separate package that depends on this one and provides an executable (though alternatively we could put an executable stanza in this library and make it optional).

**Comment by denismaier** [comment]
@iandol As helpful as Json pipes may be, that would still entail a lot of burden to Scrivener devs. **They** would have to provide a list of all citations so I'm not sure how useful this will be for what you want.

**Comment by iandol** [comment]
@denismaier — thanks for your helpful input. Scrivener compiles documents and does quite a bit of intermediate processing. One alternative is to have a tool that parses an intermediate document, i.e. Pandoc; currently Scrivener uses MMD as its internal markdown system (the original decision not to use Pandoc I think rested on its overall package size). What other options would there be?

**Comment by jgm** [comment]
I've added an optional executable `citeproc` which acts as a pipe, taking in a JSON representation of the inputs and putting out a JSON representation of the result.  Still completely untested and undocumented, but the basic code is there.

**Comment by jgm** [comment]
This is now documented. (See man page.)

**Comment by iandol** [comment]
@jgm Do you have any instructions for building the executable?

**Comment by jgm** [comment]
To build it with stack:
```
stack install --flag citeproc:executable citeproc
```
With cabal:
```
cabal update
cabal install -fexecutable citeproc
```
