### ISSUE TITLE
Sort order failure in bibliography

### ISSUE THREAD

**Issue by ah-dagdelen** [jgm/citeproc#91]
In CSL style file, I have the following sort order for the entries in bibliography:
```
    <sort>
      <key variable="language"/>
      <key variable="type"/>
      <key variable="author"/>
      <key variable="title"/>
      <key variable="issued"/>
    </sort>

```
I then manually add the headings, country name and item type, in the output format. With the help of this scheme, entries are first sorted by language, then by type, and so on... all in alphabetic order.

In the converted documents, I don't get the right order in the bibliography. The entries sorted by language are in order. Entries in the same language are kept together. So, the first sort variable does the job. However, sorting by type is not working well. There are always entries which lost their way and stand where they do not belong, e.g. an incollection item stands between books, an article stands at the end of the bibliography.

[r.zip](https://github.com/jgm/citeproc/files/7131878/r.zip)
Attached, I upload a bib file in json, the CSL style file, an org file with citations, and the output format in docx. 

Here is the version of Pandoc which I use
pandoc 2.14.1
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.11,
citeproc 0.4.1, ipynb 0.1.0.1 - Linux Mint 20.2 Cinnamon

Here is the command line which I use
pandoc -C r.org --bibliography=r.json --csl=r.csl -o r.docx

**Comment by jgm** [comment]
Can you give specific examples of entries that you think are not in the right order?

**Comment by jgm** [comment]
As far as I can see, it's working properly. I modified the style to print the type at the beginning of the entry, so you can see it:


bookWendehorst Christiane/Zöchling-Jud Brigitta, Privatrecht Einführung in die Rechtswissenschaften und ihre Methoden Teil II, 6. bs., Wien, Manz, 2016.
entry-encyclopediaWendehorst Christiane, “Art. 43 EGBGB”, Münchener Kommentar zum Bürgerlichen Gesetzbuch Band 12, ed. Hein Jan, 7. bs., München, C. H. Beck, 2018.
article-journalSerozan Rona, “Mülkiyeti saklı tutma anlaşması”, İstanbul Üniversitesi Mukayeseli Hukuk Araştırmaları Dergisi, 1968, c. 1, sy. 2, ss. 176-200.
bookSerozan Rona, Borçlar Hukuku Genel Bölüm üçüncü cilt: İfa, ifa engelleri, haksız zenginleşme, ed. Kocayusufpaşaoğlu Necip/Hatemi Hüseyin/Arpacı Abdülkadir, 7. bs., İstanbul, Filiz Kitabevi, 2016.
chapterSerozan Rona, “Mülkiyeti saklı tutma anlaşması ve teminaten temlik”, Prof. Dr. Erdoğan Moroğlu’na 65. yaş günü armağanı, 2. bs., İstanbul, Beta, 2001, ss. 987-1014.
bookAtamer Yeşim, Sözleşme özgürlüğünün sınırlandırılması sorunu çerçevesinde genel işlem şartlarının denetlenmesi, 2. bs., 2001, Beta, 2001.
bookAtamer Yeşim, Uluslararası satım sözleşmelerine ilişkin Birleşmiş Milletler Antlaşması (CISG) uyarınca satıcının yükümlülükleri ve sözleşmeye aykırılığın sonuçları, İstanbul, Beta, 2005.
bookHatemi Hüseyin, Borçlar Hukuku Genel Bölüm ikinci cilt: Sözleşme dışı sorumluluk hukuku, ed. Kocayusufpaşaoğlu Necip/Serozan Rona/Arpacı Abdülkadir, 2. bs., İstanbul, Filiz Kitabevi, 1998.
bookKocayusufpaşaoğlu Necip, Borçlar Hukuku Genel Bölüm, ed. Hatemi Hüseyin/Serozan Rona/Arpacı Abdülkadir, 7. bs., İstanbul, Filiz Kitabevi, 2017.
bookSerozan Rona, Eşya Hukuku I, 3. bs., İstanbul, Filiz Kitabevi, 2014.
bookSerozan Rona, Medeni Hukuk Genel Bölüm / Kişiler Hukuku, 8. bs., İstanbul, Vedat Kitapçılık, 2018.
chapterAtamer Yeşim, “Genel işlem koşulu mu bireysel pazarlıkla kurulan sözleşme mi?”, Yeni Türk Borçlar Kanunu ve Yeni Türk Ticaret Kanunu Sempozyumu, ed. Kırca Çiğdem, İstanbul, Vedat Kitapçılık, 2013, ss. 103-137.
chapterAtamer Yeşim, “Genel işlem şartlarının denetiminde yeni açılımlar”, Prof. Dr. Necip Kocayusufpaşaoğlu için Armağan, Ankara, Seçkin, 2004, ss. 291-331.
chapterAtamer Yeşim, “Yeni Türk Borçlar Kanunu hükümleri uyarınca genel işlem koşullarının denetlenmesi”, Türk Hukukunda Genel İşlem Şartları Sempozyumu, Ankara, BTHAE, 2012, ss. 9-73.

**Comment by jgm** [comment]
Better output, with ids too:

<div class="csl-bib-body">

<div class="csl-entry">

\|**book**\| \|wendehorstPrivatrechtEinfuhrungRechtswissenschaften2016\|
**Wendehorst Christiane**/**Zöchling-Jud Brigitta**, Privatrecht
Einführung in die Rechtswissenschaften und ihre Methoden Teil II, 6.
bs., Wien, Manz, 2016.

</div>

<div class="csl-entry">

\|**entry-encyclopedia**\| \|wendehorstArt43EGBGB2018\| **Wendehorst
Christiane**, “Art. 43 EGBGB”, Münchener Kommentar zum Bürgerlichen
Gesetzbuch Band 12, ed. **Hein Jan**, 7. bs., München, C. H. Beck, 2018.

</div>

<div class="csl-entry">

\|**article-journal**\| \|serozanMulkiyetiSakliTutma1968\| **Serozan
Rona**, “Mülkiyeti saklı tutma anlaşması”, İstanbul Üniversitesi
Mukayeseli Hukuk Araştırmaları Dergisi, 1968, c. 1, sy. 2, ss. 176-200.

</div>

<div class="csl-entry">

\|**book**\| \|serozanBorclarHukukuGenel2016\| **Serozan Rona**, Borçlar
Hukuku Genel Bölüm üçüncü cilt: İfa, ifa engelleri, haksız zenginleşme,
ed. **Kocayusufpaşaoğlu Necip**/**Hatemi Hüseyin**/**Arpacı
Abdülkadir**, 7. bs., İstanbul, Filiz Kitabevi, 2016.

</div>

<div class="csl-entry">

\|**chapter**\| \|serozanMulkiyetiSakliTutma2001\| **Serozan Rona**,
“Mülkiyeti saklı tutma anlaşması ve teminaten temlik”, Prof. Dr. Erdoğan
Moroğlu’na 65. yaş günü armağanı, 2. bs., İstanbul, Beta, 2001, ss.
987-1014.

</div>

<div class="csl-entry">

\|**book**\| \|atamerSozlesmeOzgurlugununSinirlandirilmasi2001\|
**Atamer Yeşim**, Sözleşme özgürlüğünün sınırlandırılması sorunu
çerçevesinde genel işlem şartlarının denetlenmesi, 2. bs., 2001, Beta,
2001.

</div>

<div class="csl-entry">

\|**book**\| \|atamerUluslararasiSatimSozlesmelerine2005\| **Atamer
Yeşim**, Uluslararası satım sözleşmelerine ilişkin Birleşmiş Milletler
Antlaşması (CISG) uyarınca satıcının yükümlülükleri ve sözleşmeye
aykırılığın sonuçları, İstanbul, Beta, 2005.

</div>

<div class="csl-entry">

\|**book**\| \|hatemiBorclarHukukuGenel1998\| **Hatemi Hüseyin**,
Borçlar Hukuku Genel Bölüm ikinci cilt: Sözleşme dışı sorumluluk hukuku,
ed. **Kocayusufpaşaoğlu Necip**/**Serozan Rona**/**Arpacı Abdülkadir**,
2. bs., İstanbul, Filiz Kitabevi, 1998.

</div>

<div class="csl-entry">

\|**book**\| \|kocayusufpasaogluBorclarHukukuGenel2017\|
**Kocayusufpaşaoğlu Necip**, Borçlar Hukuku Genel Bölüm, ed. **Hatemi
Hüseyin**/**Serozan Rona**/**Arpacı Abdülkadir**, 7. bs., İstanbul,
Filiz Kitabevi, 2017.

</div>

<div class="csl-entry">

\|**book**\| \|serozanEsyaHukuku2014\| **Serozan Rona**, Eşya Hukuku I,
3. bs., İstanbul, Filiz Kitabevi, 2014.

</div>

<div class="csl-entry">

\|**book**\| \|serozanMedeniHukukGenel2018\| **Serozan Rona**, Medeni
Hukuk Genel Bölüm / Kişiler Hukuku, 8. bs., İstanbul, Vedat Kitapçılık,
2018.

</div>

<div class="csl-entry">

\|**chapter**\| \|atamerGenelIslemKosulu2013\| **Atamer Yeşim**, “Genel
işlem koşulu mu bireysel pazarlıkla kurulan sözleşme mi?”, Yeni Türk
Borçlar Kanunu ve Yeni Türk Ticaret Kanunu Sempozyumu, ed. **Kırca
Çiğdem**, İstanbul, Vedat Kitapçılık, 2013, ss. 103-137.

</div>

<div class="csl-entry">

\|**chapter**\| \|atamerGenelIslemSartlarinin2004\| **Atamer Yeşim**,
“Genel işlem şartlarının denetiminde yeni açılımlar”, Prof. Dr. Necip
Kocayusufpaşaoğlu için Armağan, Ankara, Seçkin, 2004, ss. 291-331.

</div>

<div class="csl-entry">

\|**chapter**\| \|atamerYeniTurkBorclar2012\| **Atamer Yeşim**, “Yeni
Türk Borçlar Kanunu hükümleri uyarınca genel işlem koşullarının
denetlenmesi”, Türk Hukukunda Genel İşlem Şartları Sempozyumu, Ankara,
BTHAE, 2012, ss. 9-73.

</div>

</div>

**Comment by jgm** [comment]
Relevant sort keys from trace output:

```
[(ItemId {unItemId = "serozanBorclarHukukuGenel2016"},[SortKeyValue Ascending (Just ["tr"]),SortKeyValue Ascending (Just ["book"]),SortKeyValue Ascending (Just ["Serozan","Rona"]),SortKeyValue Ascending (Just ["Bor\231lar","Hukuku","Genel","B\246l\252m","\252\231\252nc\252","cilt:","\304fa","ifa","engelleri","haks\305z","zenginle\351me"]),SortKeyValue Ascending (Just ["p0000020160000"])])

,(ItemId {unItemId = "serozanMulkiyetiSakliTutma2001"},[SortKeyValue Ascending (Just ["tr"]),SortKeyValue Ascending (Just ["chapter"]),SortKeyValue Ascending (Just ["Serozan","Rona"]),SortKeyValue Ascending (Just ["M\252lkiyeti","sakl\305","tutma","anla\351mas\305","ve","teminaten","temlik"]),SortKeyValue Ascending (Just ["p0000020010000"])])

,(ItemId {unItemId = "atamerSozlesmeOzgurlugununSinirlandirilmasi2001"},[SortKeyValue Ascending (Just ["Tr"]),SortKeyValue Ascending (Just ["book"]),SortKeyValue Ascending (Just ["Atamer","Ye\351im"]),SortKeyValue Ascending (Just ["S\246zle\351me","\246zg\252rl\252\287\252n\252n","s\305n\305rland\305r\305lmas\305","sorunu","\231er\231evesinde","genel","i\351lem","\351artlar\305n\305n","denetlenmesi"]),SortKeyValue Ascending (Just ["p0000020010000"])])
```
I'm wondering whether the fact that `Tr` is capitalized in the last one is making a difference?

**Comment by jgm** [comment]
OK, changing `Tr` to `tr` in the bibliography, we get:

<div class="csl-bib-body">

<div class="csl-entry">

\|**book**\| \|wendehorstPrivatrechtEinfuhrungRechtswissenschaften2016\|
**Wendehorst Christiane**/**Zöchling-Jud Brigitta**, Privatrecht
Einführung in die Rechtswissenschaften und ihre Methoden Teil II, 6.
bs., Wien, Manz, 2016.

</div>

<div class="csl-entry">

\|**entry-encyclopedia**\| \|wendehorstArt43EGBGB2018\| **Wendehorst
Christiane**, “Art. 43 EGBGB”, Münchener Kommentar zum Bürgerlichen
Gesetzbuch Band 12, ed. **Hein Jan**, 7. bs., München, C. H. Beck, 2018.

</div>

<div class="csl-entry">

\|**article-journal**\| \|serozanMulkiyetiSakliTutma1968\| **Serozan
Rona**, “Mülkiyeti saklı tutma anlaşması”, İstanbul Üniversitesi
Mukayeseli Hukuk Araştırmaları Dergisi, 1968, c. 1, sy. 2, ss. 176-200.

</div>

<div class="csl-entry">

\|**book**\| \|atamerSozlesmeOzgurlugununSinirlandirilmasi2001\|
**Atamer Yeşim**, Sözleşme özgürlüğünün sınırlandırılması sorunu
çerçevesinde genel işlem şartlarının denetlenmesi, 2. bs., 2001, Beta,
2001.

</div>

<div class="csl-entry">

\|**book**\| \|atamerUluslararasiSatimSozlesmelerine2005\| **Atamer
Yeşim**, Uluslararası satım sözleşmelerine ilişkin Birleşmiş Milletler
Antlaşması (CISG) uyarınca satıcının yükümlülükleri ve sözleşmeye
aykırılığın sonuçları, İstanbul, Beta, 2005.

</div>

<div class="csl-entry">

\|**book**\| \|hatemiBorclarHukukuGenel1998\| **Hatemi Hüseyin**,
Borçlar Hukuku Genel Bölüm ikinci cilt: Sözleşme dışı sorumluluk hukuku,
ed. **Kocayusufpaşaoğlu Necip**/**Serozan Rona**/**Arpacı Abdülkadir**,
2. bs., İstanbul, Filiz Kitabevi, 1998.

</div>

<div class="csl-entry">

\|**book**\| \|kocayusufpasaogluBorclarHukukuGenel2017\|
**Kocayusufpaşaoğlu Necip**, Borçlar Hukuku Genel Bölüm, ed. **Hatemi
Hüseyin**/**Serozan Rona**/**Arpacı Abdülkadir**, 7. bs., İstanbul,
Filiz Kitabevi, 2017.

</div>

<div class="csl-entry">

\|**book**\| \|serozanBorclarHukukuGenel2016\| **Serozan Rona**, Borçlar
Hukuku Genel Bölüm üçüncü cilt: İfa, ifa engelleri, haksız zenginleşme,
ed. **Kocayusufpaşaoğlu Necip**/**Hatemi Hüseyin**/**Arpacı
Abdülkadir**, 7. bs., İstanbul, Filiz Kitabevi, 2016.

</div>

<div class="csl-entry">

\|**book**\| \|serozanEsyaHukuku2014\| **Serozan Rona**, Eşya Hukuku I,
3. bs., İstanbul, Filiz Kitabevi, 2014.

</div>

<div class="csl-entry">

\|**book**\| \|serozanMedeniHukukGenel2018\| **Serozan Rona**, Medeni
Hukuk Genel Bölüm / Kişiler Hukuku, 8. bs., İstanbul, Vedat Kitapçılık,
2018.

</div>

<div class="csl-entry">

\|**chapter**\| \|atamerGenelIslemKosulu2013\| **Atamer Yeşim**, “Genel
işlem koşulu mu bireysel pazarlıkla kurulan sözleşme mi?”, Yeni Türk
Borçlar Kanunu ve Yeni Türk Ticaret Kanunu Sempozyumu, ed. **Kırca
Çiğdem**, İstanbul, Vedat Kitapçılık, 2013, ss. 103-137.

</div>

<div class="csl-entry">

\|**chapter**\| \|atamerGenelIslemSartlarinin2004\| **Atamer Yeşim**,
“Genel işlem şartlarının denetiminde yeni açılımlar”, Prof. Dr. Necip
Kocayusufpaşaoğlu için Armağan, Ankara, Seçkin, 2004, ss. 291-331.

</div>

<div class="csl-entry">

\|**chapter**\| \|atamerYeniTurkBorclar2012\| **Atamer Yeşim**, “Yeni
Türk Borçlar Kanunu hükümleri uyarınca genel işlem koşullarının
denetlenmesi”, Türk Hukukunda Genel İşlem Şartları Sempozyumu, Ankara,
BTHAE, 2012, ss. 9-73.

</div>

<div class="csl-entry">

\|**chapter**\| \|serozanMulkiyetiSakliTutma2001\| **Serozan Rona**,
“Mülkiyeti saklı tutma anlaşması ve teminaten temlik”, Prof. Dr. Erdoğan
Moroğlu’na 65. yaş günü armağanı, 2. bs., İstanbul, Beta, 2001, ss.
987-1014.

</div>

</div>

Is this correct?

**Comment by ah-dagdelen** [comment]
Thanks a lot!

This order is correct. Changing `Tr` to `tr` or vice versa solves the problem. Capitalized ones and uncapitalized ones are kept together. Following uncapitalized ones, entries with capitalized language info are printed.

I'm sorry for reporting this. I should have seen that.

**Comment by ah-dagdelen** [comment]
Unlike Zotero/citeproc-js, sorting is case sensitive.

**Comment by jgm** [comment]
I don't regard this difference as a bug, if case insensitivity is not specified in the CSL spec.

**Comment by ah-dagdelen** [comment]
I didn't see any info about case sensivity in the CSL spec in this regard.

Before posting this issue, I didn't realize that some of the entries had typing error in the language field. I hadn't noticed the difference in capitalisation. I only compared outputs between Pandoc and Zotero.

Sorry again for opennig this issue. This is my fault.

But it might be thinkable that the case insensitivity in alphabetic sort order would be a better choice.

**Comment by jgm** [comment]
Certainly in the special case of `lang`, it should be case-insensitive.
In general, I don't see why...and I doubt it will make much difference in practice.

**Comment by ah-dagdelen** [comment]
In this particular example, it makes difference:

1) Some Author, Thoughts on Civil Law, 1989.
2) Some Author, Thoughts on civil life, 1989.

Normall, one would expect that the first item precedes in the bibliography. But no, the second one would be placed in front of the first item when we sort case sensitiv. Like sorting words in dictionaries, they are not case sensitive.

**Comment by jgm** [comment]
Right, that's true.

**Comment by jgm** [comment]
Moved to case-insensitive sorting.
