### ISSUE TITLE
position="subsequent" does no evaluate to false inside the <bibliography> element

### ISSUE THREAD

**Issue by badumont** [jgm/citeproc#99]
Using citeproc 0.6, the `position` attribute of `<if>` may evaluate to true, whereas the CSL specification states that

  > When called within the scope of cs:bibliography, position tests “false”.

For instance, with the following CSL file:

```
<?xml version="1.0" encoding="utf-8"?>
<style
    xmlns="http://purl.org/net/xbiblio/csl"
    class="note"
    version="1.0">
  <info>
    <id />
    <title />
  </info>
  <citation>
    <layout>
      <names variable="author">
        <name form="long"/>
      </names>
    </layout>
  </citation>
  <bibliography>
    <layout>
      <choose>
        <if position="subsequent">
          <names variable="author">
            <name form="short"/>
          </names>
        </if>
        <else>
          <names variable="author">
            <name form="long"/>
          </names>
        </else>
      </choose>
    </layout>
  </bibliography>
</style>
```

I get the following result:

```
pandoc -C --csl=test.csl -t plain <<< '
---
references:
- type: book
  id: Doe
  author:
  - family: Doe
  - given: John
---

[@Doe]
'
[1]

Doe

[1] Doe, John
```
where "Doe, John" should appear both in the citation and the bibliography.

**Comment by jgm** [comment]
OK, I think I've fixed this, but my fix gives "John Doe" instead of "Doe, John" in the bibliography. Is that correct?

**Comment by badumont** [comment]
Thanks! If I understand [the specification](https://docs.citationstyles.org/en/1.0.1/specification.html#id49) well, it should be "John Doe" everywhere when only the instruction `form="long"` is given.
